version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/nextwork-web-project
hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 60
      runas: ubuntu
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 120
      runas: ubuntu
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 60
      runas: ubuntu
  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 60
      runas: ubuntu
