version: 0.2
phases:
  install:
    commands:
      - apt-get update -y
      - apt-get install -y openjdk-17-jdk maven
  build:
    commands:
      - mvn clean package -DskipTests
artifacts:
  files:
    - target/*.jar
    - appspec.yml
    - scripts/**/*
